app/urls.py
from django.conf.urls import url
from .views import add_edit_feature, list_features, delete_feature

urlpatterns = [
    url(r'^/$', add_edit_feature, name='add_edit_feature'),
    url(r'^/list/$', list_features, name='list_features'),
    url(r'^/edit/(?P<id>[\d]+)/$', add_edit_feature, name='edit_feature'),
    url(r'^/delete/(?P<id>[\d]+)/$', delete_feature, name='delete_feature'),
]

feature_plus/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^features', include('app.urls', namespace='features')),
]

app/models.py
from __future__ import unicode_literals, absolute_import

from django.db import models

PRIORITY_ONE = 1

CLIENTS = (
    ('Client A', 'Client A'),
    ('Client B', 'Client B'),
    ('Client C', 'Client C'),
)

PRODUCT_AREAS = (
    ('Policies', 'Policies'),
    ('Billing', 'Billing'),
    ('Claims', 'Claims'),
    ('Reports', 'Reports'),
)


class Feature(models.Model):
    """
    Represents a Feature object.
    """
    title = models.CharField(max_length=100, help_text='Title', unique=True)
    description = models.TextField(help_text='Description')
    clients = models.CharField(max_length=35, choices=CLIENTS, help_text='Client')
    priority = models.PositiveIntegerField(help_text='Client Priority')
    target_date = models.DateTimeField(help_text='Date Expected')
    ticket_url = models.URLField(help_text='Ticket URL')
    product_area = models.CharField(max_length=35, choices=PRODUCT_AREAS, help_text='Product Area')

    class Meta:
        verbose_name = 'Feature'
        verbose_name_plural = 'Features'
        unique_together = ('title', 'clients', 'priority')

    def __unicode__(self):
        return self.title

app/forms.py
from __future__ import unicode_literals, absolute_import

from datetime import datetime

from django import forms
from .models import Feature

__author__ = 'inspaya'


class FeatureForm(forms.ModelForm):
    """
    Custom Data Entry Form
    """
    class Meta:
        model = Feature
        fields = '__all__'

    def clean_target_date(self):
        target_date = self.cleaned_data['target_date']
        return datetime.strftime(target_date, '%Y-%m-%dT%H:%MZ')

app/views.py
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import loader, RequestContext

from .forms import FeatureForm
from .models import Feature
from .services import update_other_priorities


def add_edit_feature(request, id=None):
    """
    Add/Edit Feature
    :param request:
    :return:
    """
    feature = None
    if request.method == 'POST':
        feature = Feature.objects.filter(title=request.POST['title']).first()
        feature_form = FeatureForm(request.POST, instance=feature)
        if feature_form.is_valid():
            update_other_priorities(feature, **feature_form.cleaned_data)
            return HttpResponseRedirect(reverse('features:list_features'))
    else:
        if id:
            feature = Feature.objects.filter(id=int(id)).first()

        feature_form = FeatureForm(instance=feature)

    return render_to_response('add_edit_features.html',
                              {'feature_form': feature_form},
                              RequestContext(request)
                              )


def list_features(request):
    """
    Return List of available features
    :param request:
    :return:
    """
    features = Feature.objects.all()
    template = loader.get_template('list_features.html')
    context = RequestContext(request, {'list_of_features': features})
    return HttpResponse(template.render(context))


def delete_feature(request, id):
    """
    Deletes a feature from the DB
    :param request:
    :param id:
    :return:
    """
    try:
        Feature.objects.get(id=int(id)).delete()
    except Feature.DoesNotExist:
        return render_to_response('404.html', {'not_found': "Feature not found."})

    return HttpResponseRedirect(reverse('features:list_features'))

app/templates/add_edit_features.html
{% extends "base.html" %}
{% block left_content %}
<div class="col-md-8">
    <h3>Add/Edit Feature</h3>

    <form class="form-horizontal" action="{% url 'features:add_edit_feature' %}" method="POST">
        {% csrf_token %}
        {{ feature_form.non_field_errors }}
        <div class="form-group"><!--has-error has-feedback-->
            {{ feature_form.title.errors }}
            <label class="col-sm-2 control-label">Title</label>

            <div class="col-sm-5">
                <input type="text" class="form-control" name="title"
                       value="{{ feature_form.title.value|default_if_none:'' }}"
                       placeholder="" />
                <!--<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>-->
                <!--<span id="titleError" class="sr-only">(error)</span>-->
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.description.errors }}
            <label for="description" class="col-sm-2 control-label">Description</label>

            <div class="col-sm-5">
                <textarea class="form-control" id="description" name="description"
                          value="{{ feature_form.description|default_if_none:'' }}" ></textarea>
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.clients.errors }}
            <label class="col-sm-2 control-label">Clients</label>

            <div class="col-sm-5">
                <select class="form-control" id="clients" name="clients">
                    {% for client in feature_form.clients %}
                    <option value="{{ client }}"></option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.priority.errors }}
            <label for="priority" class="col-sm-2 control-label">Priority</label>

            <div class="col-sm-1">
                <input type="number" class="form-control" id="priority" name="priority"
                       value="{{ feature_form.priority.value|default_if_none:'' }}" placeholder="" >
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.target_date.errors }}
            <label for="target_date" class="col-sm-2 control-label">Target Date</label>

            <div class="col-sm-2">
                <input type="date" class="form-control" id="target_date" name="target_date"
                       value="{{ feature_form.target_date.value|default_if_none:'' }}"
                       placeholder="" ><span>YYYY-MM-DD</span>
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.ticket_url.errors }}
            <label for="ticket_url" class="col-sm-2 control-label">Ticket URL</label>

            <div class="col-sm-5">
                <input type="url" class="form-control" id="ticket_url" name="ticket_url"
                       value={{ feature_form.ticket_url.value| default_if_none:'http://' }} placeholder="" />
            </div>
        </div>
        <div class="form-group">
            {{ feature_form.product_area.errors }}
            <label for="product_area" class="col-sm-2 control-label">Product Area</label>

            <div class="col-sm-5">
                <select class="form-control" id="product_area" name="product_area">
                    {% for product in feature_form.product_area %}
                    <option value="{{ product }}"></option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">&nbsp;</label>

            <div class="col-sm-5">
                <input class="btn btn-primary" type="submit" value="Save">
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>FeaturePlus - Demo</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/featureplus.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<h1>FeaturePlus</h1>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<div class="row" class="col-md-12">
    {% block left_content %}{% endblock %}
    {% block right_content %}{% endblock %}
    {% block not_found %}{% endblock %}
</div>
</body>
</html>

app/templates/list_features.html
{% extends "base.html" %}
{% block left_content %}
<div class="col-md-8">
    <table class="table table-hover feature_list">
        <thead><h3>List of Features</h3></thead>
        <tbody>
        <tr><td><a href="{% url 'features:add_edit_feature' %}">Add New</a></td></tr>
        <tr>
            <td>S/N</td>
            <td>Title</td>
            <td>Clients</td>
            <td>Priority</td>
            <td>Target Date</td>
            <td>Product Area</td>
            <td>Action</td>
        </tr>
        {% for feature in list_of_features%}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'features:edit_feature' feature.pk %}">{{ feature.title }}</a></td>
            <td>{{ feature.clients }}</td>
            <td>{{ feature.priority }}</td>
            <td>{{ feature.target_date }}</td>
            <td>{{ feature.product_area }}</td>
            <td><a href="{% url 'features:delete_feature' feature.pk  %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}